CraigsBlog/Models/Blogs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CraigsBlog.Models
{
    public class Blogs
    {
        [Key]
        public int Id { get; set; }
        
        public string Title { get; set; }
       
        public string Content { get; set; }

        public string Keywords { get; set; }
        
        public bool IsPublic { get; set; }

        public virtual Users Users { get; set; }
    }
}

CraigsBlog/Models/CraigsDB.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace CraigsBlog.Models
{
    public class CraigsDB: DbContext  //inheriting CraigsDB from the DbContext
    {
        public CraigsDB()
            : base("DefaultConnection")
        {
            Database.SetInitializer(new DropCreateDatabaseIfModelChanges<CraigsDB>());
        }
        public DbSet<Users> craigsUsers { get; set; } //create the link between the model and the database, use slightly different name so as not to get confused.
        public DbSet<Blogs> craigsBlogs { get; set; }
        public DbSet<Keywords> craigsKeywords { get; set; }
    }
}

CraigsBlog/Models/Keywords.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CraigsBlog.Models
{
    public class Keywords
    {
        [Key]
        public int Id { get; set; }

        public string Keyword { get; set; }
    }
}

CraigsBlog/Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CraigsBlog.Models
{
    public class Users
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a valid email address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter a valid password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        public string Name { get; set; }

        public bool IsAuthorised { get; set; }

        public virtual List<Blogs> Blogs { get; set; }

    }
}

CraigsBlog/Controllers/BlogCreationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CraigsBlog.Models;

namespace CraigsBlog.Controllers
{
    public class BlogCreationController : Controller
    {
        //
        // GET: /BlogCreation/
        public ActionResult Index()
        {
            using (CraigsDB db = new CraigsDB())
            {
                return View(db.craigsBlogs.ToList());
            }
           
        }
        
        [HttpGet]
        public ActionResult CreateBlog()
        {
            if (Session["Id"] != null)
            {
                return View();
            }

            else
            {
                return RedirectToAction("Login", "BlogUsers");
            }
        }

        [HttpPost]
        public ActionResult CreateBlog (Blogs newBlog) {
            
            using (CraigsDB db = new CraigsDB()) {
                db.craigsBlogs.Add(newBlog);
                db.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.Message = "Your blog entry has been created.";
            return View();
        }
            
        

        }
	}

CraigsBlog/Controllers/BlogUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CraigsBlog.Models;

namespace CraigsBlog.Controllers
{
    public class BlogUsersController : Controller
    {
        //
        // GET: /BlogUsers/
        public ActionResult Index()
        {
            using (CraigsDB db = new CraigsDB())
            {
                return View(db.craigsUsers.ToList());  //to see a list of table contents
            }
        }
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Registration(Users newAccount) {

            if (ModelState.IsValid)
            {
                using (CraigsDB db = new CraigsDB())
                {
                    db.craigsUsers.Add(newAccount);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = newAccount.Name + "'s account has been registered!";
            }
            else
            {
                ModelState.AddModelError("", "Please try entering your details again");
            }
            return View();

        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users registeredUser)
        {
            try { 
            using (CraigsDB db = new CraigsDB())
            {
                var usr = db.craigsUsers.Single(u => u.Email == registeredUser.Email && u.Password == registeredUser.Password); //only if the user email and password are true then it is not null and a session can be created.
                
                {
                    Session["Id"] = usr.Id.ToString();
                    Session["Email"] = usr.Email.ToString();
                    Session["Name"] = usr.Name.ToString();

                    if (Session["Email"].ToString() == "admin@admin.com") {
                        return RedirectToAction( "Index", "BlogUsers");
                    }
                    else {
                        return RedirectToAction("MembersPage", "BlogUsers");
                    }
                    
                    
                }
            }
            
         }
                    catch (Exception) // taken from http://www.codeproject.com/Articles/850062/Exception-handling-in-ASP-NET-MVC-methods-explaine
                {
                    ModelState.AddModelError("", "Login attempt has been unsuccessful.  Please try again.");
                    return View();
                }


            }
            
        

        public ActionResult Logout()
        {
            Session["Id"] = null;
            return RedirectToAction("Login");
        }

        public ActionResult MembersPage()
        {
            if (Session["Id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
	}
}

CraigsBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CraigsBlog.Models;

namespace CraigsBlog.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult publicBlogsCount()
        {
            using (CraigsDB db = new CraigsDB())
            {
                var blogtotal = (db.craigsBlogs.Where(p => (p.IsPublic == true)).Count());// checks database, counts public blogs and returns a number - puts it into variable blogtotal
                return Json(blogtotal, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GrabNewestPost()
        {
            using (CraigsDB db = new CraigsDB())
            {
                Blogs post = new Blogs();
                post = db.craigsBlogs.Where(p => (p.IsPublic == true))
                                                            .OrderByDescending(p => p.Id)
                                                            .FirstOrDefault();

                return Json(post, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetNextPost(int Id)
        {
            using (CraigsDB db = new CraigsDB())
            {
                Blogs post = new Blogs();
                post = db.craigsBlogs.Where(p => (p.IsPublic == true) && (p.Id > Id))
                                      .OrderBy(p => p.Id)
                                      .FirstOrDefault();

                return Json(post, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult GetPreviousPost(int Id)
        {
            using (CraigsDB db = new CraigsDB())
            {
                Blogs post = new Blogs();
                post = db.craigsBlogs.Where(p => (p.IsPublic == true) && (p.Id == (Id -1)))
                              .OrderBy(p => p.Id)
                              .FirstOrDefault();

                return Json(post, JsonRequestBehavior.AllowGet);
            }
        }

        }
    }

CraigsBlog/Views/BlogCreation/CreateBlog.cshtml
@model CraigsBlog.Models.Blogs

@{
    ViewBag.Title = "Create Blog";
}

<h2>Create Blog</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true)
        @if (ViewBag.Message != null)
        {
            @ViewBag.Message
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.IsPublic, new { @Value = true }) <!--adding hiden checkbox now because you cant later-->

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Post" class="btn btn-default" />
            </div>
        </div>
   
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CraigsBlog/Views/BlogCreation/Index.cshtml
@model IEnumerable<CraigsBlog.Models.Blogs>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublic)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.CheckBoxFor(modelItem => item.IsPublic)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

CraigsBlog/Views/BlogUsers/Index.cshtml
@model IEnumerable<CraigsBlog.Models.Users>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAuthorised)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAuthorised)
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        
    </tr>
}

</table>

CraigsBlog/Views/BlogUsers/Login.cshtml
@model CraigsBlog.Models.Users

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary " />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CraigsBlog/Views/BlogUsers/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}

<h2>Logout</h2>

CraigsBlog/Views/BlogUsers/MembersPage.cshtml
@{
    ViewBag.Title = "MembersPage";
}

<h2>MembersPage</h2>

@if (Session["Id"] != null) {
    
    <p>
        Welcome! @Session["Name"].ToString() You are now logged in.
    </p>
}

CraigsBlog/Views/BlogUsers/Registration.cshtml
@model CraigsBlog.Models.Users

@{
    ViewBag.Title = "Registration";
}

<h2>Registration</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)
        @if (ViewBag.Message != null)
        {
            @ViewBag.Message
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CraigsBlog/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section Scripts {

    <script>


        $(document).ready(function () {
            $.ajax({
                url: "/Home/publicBlogsCount",
                type: "GET",
                dataType: "json",
                success: getBlogNumber, // converts the count of public blog posts to string to an intiger.
                error: function (error) {
                    alert(error.responseText);
                }

            });
        });

        var publicBlogTotal;

        function getBlogNumber(data) {
            publicBlogTotal = parseInt(data);
        }






        var InUseBlog;  // Id data will get put into this


        $(document).ready(function () {
            $.ajax({
                url: "/Home/GrabNewestPost",
                type: "GET",
                dataType: "json",
                success: displayBlogPosts, // this is name of functions to insert posts into html using jQuery
                error: function (error) {
                    alert(error.responseText);
                }

            });
        });



        function displayBlogPosts(data) {

            InUseBlog = data.Id;
            $("#Title").text(data.Title);  //make id for title html
            $("#Content").text(data.Content); //make id for content html
            currentblogposition();

        }
        function currentblogposition() {
            if (InUseBlog != 1) {
                $("#Previous").prop("disabled", false)
            }
            else {
                $("#Previous").prop("disabled", true)
            }
            if (InUseBlog == publicBlogTotal) {
                $("#Next").prop("disabled", true)
            }
            else {
                $("#Next").prop("disabled", false)
            }
        }

        $("#Previous").click(function () {
            $.ajax({
                url: "/Home/GetPreviousPost/?Id=" + InUseBlog,
                type: "GET",
                dataType: "json",
                success: displayBlogPosts,
                error: function (error) {
                    alert(error.responseText);
                }
            });
        })

        $("#Next").click(function () {

            $.ajax({
                url: "/Home/GetNextPost/?Id=" + InUseBlog,  //says that the current Id value is whatever is in InUseBlog Id value
                type: "GET",
                dataType: "json",
                success: displayBlogPosts,
                error: function (error) {
                    alert(error.responseText);
                }




            });
        })



    </script>
}


    <div class="row">
       <div class="col-sm-6 col-sm-offset-3">
            <div class="well">

                <h1 id="Title"></h1>
                <p id="Content"></p>

               
            </div>
        </div>

        <div class="col-sm-3 sidenav">
            <div class="well">
                <ul id="similarArticles">
                    <li><a href="#"><b>Apple</b></a></li>
                    <li><a href="#"><b>Google</b></a></li>
                    <li><a href="#"><b>Amazon</b></a></li>
                </ul>
            </div>
        </div>
       
       <div class ="row">
        <div class="col-sm-2 col-sm-offset-6">
            <form action="form">

                <button type="button" class="btn btn-default btn-sm value" id="Previous" value="Previous">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </button>

                <button type="button" class="btn btn-default btn-sm value" id="Next" value="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </button>
            </form>


            </div>
           </div>

        </div>


        @*<input type="button" class="btn btn-default" id="Previous" value="Previous" />
            <input type="button" class="btn btn-default" id="Next" value="next" />*@

CraigsBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Everyday Things Blog", "Index", "Home", null, new { id="logo", @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
                @Html.Partial("_menuRight")
            </div>
        </div>
    </div>

    <br />
    <br />
    <div class="container body-content col-lg-12">
        @RenderBody()

      
        
        <hr />
       
        <footer id="end">
            <p>&copy; @DateTime.Now.Year - Craig Cathcart</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CraigsBlog/Views/Shared/_menuRight.cshtml
<ul class="nav navbar-nav navbar-right">
    @if (Session["Id"] != null)
    {
        <li>@Html.ActionLink("Logout", "Logout", "BlogUsers")</li>
        <li>@Html.ActionLink("Create a blog" , "CreateBlog", "BlogCreation")</li>
        
      
    }
        

    @if (Session["Id"] == null)
    {
        <li>@Html.ActionLink("Login", "Login", "BlogUsers")</li>
        <li>@Html.ActionLink("Registration", "Registration", "BlogUsers")</li>
        
    }
</ul>